version: '3.9'

services:
  api:
    image: ${IMAGE_REF:-mini-project-api:latest}
    build:
      context: .
    ports:
      - '${PORT:-3000}:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/tasksdb
      JWT_SECRET: ${JWT_SECRET:-local-secret}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/app/db/migrations:ro
    command: ["node", "dist/index.js"]

  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data:
